import Head from "next/head";
import { useRouter } from "next/router";
import { useRef } from "react";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import withAuth from "../components/testHOC";

const Home = () => {
  const inputRef = useRef();
  const route = useRouter();

  const [user, setUser] = useState(false);

  console.log(route);

  const handleSearchRepo = () => {
    //add some kind of validation
    route.push(`/${inputRef.current.value}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title> GitHub </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input ref={inputRef} />
        <button onClick={handleSearchRepo}> Show repos </button>
      </main>
    </div>
  );
};

export default withAuth(Home);
